# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"!\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"s\n\x12SynthesizeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\x12\x15\n\rsampling_rate\x18\x04 \x01(\x05\x12\x10\n\x08\x64uration\x18\x05 \x01(\x02\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x9a\x01\n\x13HealthCheckResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.tts.HealthCheckResponse.ServingStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\x8d\x01\n\nTTSService\x12=\n\nSynthesize\x12\x16.tts.SynthesizeRequest\x1a\x17.tts.SynthesizeResponse\x12@\n\x0bHealthCheck\x12\x17.tts.HealthCheckRequest\x1a\x18.tts.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=18
  _globals['_SYNTHESIZEREQUEST']._serialized_end=51
  _globals['_SYNTHESIZERESPONSE']._serialized_start=53
  _globals['_SYNTHESIZERESPONSE']._serialized_end=168
  _globals['_HEALTHCHECKREQUEST']._serialized_start=170
  _globals['_HEALTHCHECKREQUEST']._serialized_end=207
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=210
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=364
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=306
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=364
  _globals['_TTSSERVICE']._serialized_start=367
  _globals['_TTSSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
